<?xml version='1.0'?>
<!--Define the internal DTD subset-->
<!DOCTYPE action[
	<!ELEMENT action (Entity+)>
	<!ELEMENT Entity (name,flag,outgoing_edges)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT flag (#PCDATA)>
	<!ELEMENT outgoing_edges (isa,includes,part_of,contains,similar,related)>
	<!ELEMENT isa (edge*)>
	<!ELEMENT includes (edge*)>
	<!ELEMENT part_of (edge*)>
	<!ELEMENT contains (edge*)>
	<!ELEMENT similar (edge*)>
	<!ELEMENT related (edge*)>
	<!ELEMENT edge (other,co_occur)>
	<!ELEMENT other (#PCDATA)>
	<!ELEMENT co_occur (#PCDATA)>
	<!ELEMENT property (prop*)>
	<!ELEMENT prop (#PCDATA)>
]>
<action>
	<Entity>
		<name>HumanRA</name>
		<flag>0</flag>
		<outgoing_edges>
			<isa>
			</isa>
			<includes>
				<edge>
					<other>HandRA</other>
					<co_occur>1</co_occur>
				</edge>
				<edge>
					<other>FaceRA</other>
					<co_occur>1</co_occur>
				</edge>
				<edge>
					<other>LegRA</other>
					<co_occur>1</co_occur>
				</edge>
			</includes>
			<part_of>
			</part_of>
			<contains>
			</contains>
			<similar>
			</similar>
			<related>
				<edge>
					<other>Human</other>
					<co_occur>1</co_occur>
				</edge>
				<edge>
					<other>HumanRO</other>
					<co_occur>1</co_occur>
				</edge>
			</related>
		</outgoing_edges>
	</Entity>
<Entity>
	<name>HandRA</name>
	<flag>0</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>HumanRA</other>
				<co_occur>1</co_occur>
			</edge>
		</isa>
		<includes>
			<edge>
				<other>Catch</other>
				<co_occur>0.8</co_occur>
			</edge>
			<edge>
				<other>Write</other>
				<co_occur>0.6</co_occur>
			</edge>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
			<edge>
				<other>Hand</other>
				<co_occur>1</co_occur>
			</edge>
			<edge>
				<other>HandRO</other>
				<co_occur>1</co_occur>
			</edge>
		</related>
	</outgoing_edges>
</Entity>
<Entity>
	<name>LegRA</name>
	<flag>0</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>HumanRA</other>
				<co_occur>1</co_occur>
			</edge>
		</isa>
		<includes>
			<edge>
				<other>Walk</other>
				<co_occur>0.9</co_occur>
			</edge>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
			<edge>
				<other>Leg</other>
				<co_occur>1</co_occur>
			</edge>
			<edge>
				<other>LegRO</other>
				<co_occur>1</co_occur>
			</edge>
		</related>
	</outgoing_edges>
</Entity>
<Entity>
	<name>FaceRA</name>
	<flag>0</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>HumanRA</other>
				<co_occur>1</co_occur>
			</edge>
		</isa>
		<includes>
			<edge>
				<other>Smile</other>
				<co_occur>0.4</co_occur>
			</edge>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
			<edge>
				<other>Face</other>
				<co_occur>1</co_occur>
			</edge>
			<edge>
				<other>FaceRO</other>
				<co_occur>1</co_occur>
			</edge>
		</related>
	</outgoing_edges>
</Entity>
<Entity>
	<name>Catch</name>
	<flag>1</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>HandRA</other>
				<co_occur>0.8</co_occur>
			</edge>
		</isa>
		<includes>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
		</related>
	</outgoing_edges>
</Entity>
	
<Entity>
	<name>Write</name>
	<flag>1</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>HandRA</other>
				<co_occur>0.6</co_occur>
			</edge>
		</isa>
		<includes>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
		</related>
	</outgoing_edges>
</Entity>
<Entity>
	<name>Walk</name>
	<flag>1</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>LegRA</other>
				<co_occur>0.9</co_occur>
			</edge>
		</isa>
		<includes>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
		</related>
	</outgoing_edges>
</Entity>
	
<Entity>
	<name>Smile</name>
	<flag>1</flag>
	<outgoing_edges>
		<isa>
			<edge>
				<other>FaceRA</other>
				<co_occur>0.4</co_occur>
			</edge>
		</isa>
		<includes>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
		</related>
	</outgoing_edges>
</Entity>
	
<Entity>
	<name>Null</name>
	<flag>0</flag>
	<outgoing_edges>
		<isa>			
		</isa>
		<includes>
		</includes>
		<part_of>
		</part_of>
		<contains>
		</contains>
		<similar>
		</similar>
		<related>
		</related>
	</outgoing_edges>
</Entity>
		
</action>
